GameStore.Web/Controllers/PaymentController.cs
using System.Net;
using System.Web.Mvc;
using GameStore.Domain.Core.DomainModels;
using GameStore.Domain.Core.Enums;
using GameStore.Services.Interfaces;
using GameStore.Web.PaymentStrategy;
using GameStore.Web.PaymentStrategy.Interfaces;
using Rotativa;

namespace GameStore.Web.Controllers
{
    public class PaymentController : Controller
    {
        private readonly IPaymentContext _paymentContext;
        private readonly IOrderManager _orderManager;

        public PaymentController(IPaymentContext paymentManager, IOrderManager orderManager)
        {
            _paymentContext = paymentManager;
            _orderManager = orderManager;
        }

        public ActionResult CreatePayment(PaymentMethodsEnum method, Order order)
        {
            order.Status = OrderStatusEnum.Paid;
            _orderManager.EditOrder(order);

            return _paymentContext.CreatePayment(method);
        }

        [HttpPost]
        public HttpStatusCode DummyPaymentResponse()
        {
            return HttpStatusCode.OK;
        }

        public ActionResult GenerateInvoiceFile()
        {
            return View("PdfInvoice");
        }
    }
}

GameStore.Web/Views/Payment/IBoxTerminalPayForm.cshtml
@{
    ViewBag.Title = "IBoxTerminalPayForm";
}

<h2>IBox Terminal</h2> @*todo : create form*@

@using (Html.BeginForm("DummyPaymentResponse", "Payment", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.Label("Operation number", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("cardNumber")
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Sum", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("sum")
            </div>
        </div>
    </div>
    <input type="submit" value="Pay" />
}

GameStore.Web/Views/Payment/VisaPayForm.cshtml
@{
    ViewBag.Title = "Pay";
}

@model GameStore.Domain.Core.DomainModels.Order

<h2>Visa Pay</h2>

@using (Html.BeginForm("DummyPaymentResponse", "Payment", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.Label("Card number", new { @class = "control-label col-md-2" })
            <div class = "col-md-10">
                @Html.TextBox("cardNumber")
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Date", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("date")
            </div>
        </div>

        <div class="form-group">
            @Html.Label("CVV", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("cvv")
            </div>
        </div>
    </div>
    <input type="submit" value="Pay"/>
}



















@*<div class="container">
        <div class="row">
            <div class="col-sm-12">
                <legend>Mr. Sosa:</legend>
            </div>
            <!-- panel preview -->
            <div class="col-sm-5">
                <h4>Add payment:</h4>
                <div class="panel panel-default">
                    <div class="panel-body form-horizontal payment-form">
                        <div class="form-group">
                            <label for="concept" class="col-sm-3 control-label">Concept</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" id="concept" name="concept">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="description" class="col-sm-3 control-label">Description</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" id="description" name="description">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="amount" class="col-sm-3 control-label">Amount</label>
                            <div class="col-sm-9">
                                <input type="number" class="form-control" id="amount" name="amount">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="status" class="col-sm-3 control-label">Status</label>
                            <div class="col-sm-9">
                                <select class="form-control" id="status" name="status">
                                    <option>Paid</option>
                                    <option>Unpaid</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="date" class="col-sm-3 control-label">Date</label>
                            <div class="col-sm-9">
                                <input type="date" class="form-control" id="date" name="date">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-12 text-right">
                                <button type="button" class="btn btn-default preview-add-button">
                                    <span class="glyphicon glyphicon-plus"></span> Add
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div> <!-- / panel preview -->
            <div class="col-sm-7">
                <h4>Preview:</h4>
                <div class="row">
                    <div class="col-xs-12">
                        <div class="table-responsive">
                            <table class="table preview-table">
                                <thead>
                                    <tr>
                                        <th>Concept</th>
                                        <th>Description</th>
                                        <th>Amount</th>
                                        <th>Status</th>
                                        <th>Date</th>
                                    </tr>
                                </thead>
                                <tbody></tbody> <!-- preview content goes here-->
                            </table>
                        </div>
                    </div>
                </div>
                <div class="row text-right">
                    <div class="col-xs-12">
                        <h4>Total: <strong><span class="preview-total"></span></strong></h4>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12">
                        <hr style="border:1px dashed #dddddd;">
                        <button type="button" class="btn btn-primary btn-block">Submit all and finish</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>

        function calc_total(){
            var sum = 0;
            $('.input-amount').each(function(){
                sum += parseFloat($(this).text());
            });
            $(".preview-total").text(sum);
        }
        $(document).on('click', '.input-remove-row', function(){
            var tr = $(this).closest('tr');
            tr.fadeOut(200, function(){
                tr.remove();
                calc_total()
            });
        });

        $(function(){
            $('.preview-add-button').click(function(){
                var form_data = {};
                form_data["concept"] = $('.payment-form input[name="concept"]').val();
                form_data["description"] = $('.payment-form input[name="description"]').val();
                form_data["amount"] = parseFloat($('.payment-form input[name="amount"]').val()).toFixed(2);
                form_data["status"] = $('.payment-form #status option:selected').text();
                form_data["date"] = $('.payment-form input[name="date"]').val();
                form_data["remove-row"] = '<span class="glyphicon glyphicon-remove"></span>';
                var row = $('<tr></tr>');
                $.each(form_data, function( type, value ) {
                    $('<td class="input-'+type+'"></td>').html(value).appendTo(row);
                });
                $('.preview-table > tbody:last').append(row);
                calc_total();
            });
        });

    </script>*@