GameStore.Web/ViewModels/CreateGameViewModel.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace GameStore.Web.ViewModels
{
    public class CreateGameViewModel
    {
        public CreateGameViewModel()
        {
            SelectedGenres = new List<int>();
            SelectedPlatforms = new List<int>();
            SelectedPublishers = new List<int>();
        }

        [HiddenInput(DisplayValue = false)]
        public int Id { get; set; }

        [Required(ErrorMessage = "This field required")]
        [MinLength(2,ErrorMessage = "Can't be less than 2"), MaxLength(50, ErrorMessage = "Name length 50 symbols")]
        public string Name { get; set; }

        [Required(ErrorMessage = "This field required")]
        [Display(Name = "Unique Key")]
        [MinLength(2, ErrorMessage = "Minimum 2 char's"), MaxLength(8, ErrorMessage = "Maximum 8 char's")]
        [RegularExpression(@"^[^<>.,?;:'()!~%\-_@#/*""\s]+$", ErrorMessage = "Shouldn't contains special char's or whitespaces")]
        public string Key { get; set; }

        [Required(ErrorMessage = "This field required")]
        public string Description { get; set; }

        [DisplayName("Price ($)")]
        [DataType(DataType.Currency, ErrorMessage = "Invalid price")]
        [Range(0.01, 9999.99, ErrorMessage = "From 0.01 to 9999.99")]
        [Required(ErrorMessage = "This field required")]
        public decimal Price { get; set; }

        [Display(Name = "Units in stock")]
        [Required(ErrorMessage = "This field required")]
        [Range(0, short.MaxValue, ErrorMessage = "From 0 to 9999")]
        public short UnitsInStock { get; set; }

        [Required(ErrorMessage = "This field required")]
        public bool Discontinued { get; set; }

        public MultiSelectList AllGenres { get; set; }

        [Display(Name = "Genres")]
        [Required(ErrorMessage = "Choose one or more")]
        public List<int> SelectedGenres { get; set; }

        public MultiSelectList AllPlatforms { get; set; }

        [Display(Name = "Platforms")]
        [Required(ErrorMessage = "Choose one or more")]
        public List<int> SelectedPlatforms { get; set; }

        public MultiSelectList AllPublishers { get; set; }

        [Display(Name = "Publishers")]
        [Required(ErrorMessage = "Choose one or more")]
        public List<int> SelectedPublishers { get; set; }
    }
}

GameStore.Web/ViewModels/GameViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace GameStore.Web.ViewModels
{
    public class GameViewModel
    {
        public GameViewModel()
        {
            Comments = new List<CommentViewModel>();
        }

        [HiddenInput(DisplayValue = false)]
        public int Id { get; set; }

        [Required]
        public string Key { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string Description { get; set; }

        [Required]
        public decimal Price { get; set; }

        [Required]
        public virtual short UnitsInStock { get; set; }

        [Required]
        public bool Discontinued { get; set; }

        public List<CommentViewModel> Comments { get; set; }

        [Required]
        public string Genres { get; set; }

        [Required]
        public string Platforms { get; set; }

        [Required]
        public List<string> Publishers { get; set; }

        public DateTime AddingDate { get; set; }

        public int CountOfViews { get; set; }
    }
}

GameStore.Web/Controllers/GameController.cs
using System;
using AutoMapper;
using GameStore.Domain.Core.DomainModels;
using GameStore.Services.Interfaces;
using GameStore.Web.ViewModels;
using PagedList;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Reflection;
using Org.BouncyCastle.Math;

namespace GameStore.Web.Controllers
{
    public class GameController : Controller
    {
        private readonly IGameManager _gameManager;
        private readonly IGenreManager _genreManager;
        private readonly IPlatformManager _platformManager;
        private readonly IPublisherManager _publisherManager;

        public GameController(IGameManager gameManager, IGenreManager genreManager, IPlatformManager platformTypeManager, IPublisherManager publisherManager)
        {
            _gameManager = gameManager;
            _genreManager = genreManager;
            _platformManager = platformTypeManager;
            _publisherManager = publisherManager;
        }

        [HttpGet]
        public ActionResult GetAllGames(FilterOutputModel filterOutput, int? page)
        {
            if (filterOutput == null)
            {
                filterOutput = Session["FilterState"] as FilterOutputModel;
            }

            if (filterOutput.GetType()
                .GetProperties(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static | BindingFlags.Instance)
                .Any(property => property.CanRead && property.GetValue(filterOutput, null) != null))
            {
                var result = _gameManager.GetFilteredResult(Mapper.Map<FilterOutputModel, IFilterModel>(filterOutput));

                int perPage = result.Count();

                if (Int32.TryParse(filterOutput.ItemsPerPage, out int number))
                {
                    if (number != 0) perPage = number;
                }


                var mappingResult = Mapper.Map<IEnumerable<Game>, IEnumerable<GameViewModel>>(result).ToPagedList(page ?? 1, perPage);
                var model = new GamesWithFilterComplexModel() { GameList = mappingResult, Filter = GetFilterModel() };

                Session["FilterState"] = filterOutput;

                return View("AllGames", model);
            }
            else
            {
                Session["FilterState"] = null;

                var gamesFromDb = _gameManager.GetAllGames().ToList();

                var mappingResult = Mapper.Map<IEnumerable<Game>, IEnumerable<GameViewModel>>(gamesFromDb).ToPagedList(page ?? 1, 2);
                var model = new GamesWithFilterComplexModel() { GameList = mappingResult, Filter = GetFilterModel() };

                return View("AllGames", model);
            }
        }

        [HttpGet]
        public ActionResult CreateGame()
        {
            var gameViewModel = new CreateGameViewModel();

            var genresFromDb = _genreManager.GetAllGenres().ToList();
            var platformsFromDb = _platformManager.GetAllPlatforms().ToList();
            var publishersFromDb = _publisherManager.GetAllPublishers().ToList();

            gameViewModel.AllGenres = new MultiSelectList(genresFromDb.OrderBy(i => i.Category), "Id", "Name", "Category");
            gameViewModel.AllPlatforms = new MultiSelectList(platformsFromDb.OrderBy(i => i.Type), "Id", "Type");
            gameViewModel.AllPublishers = new MultiSelectList(publishersFromDb.OrderBy(i => i.CompanyName), "Id", "CompanyName");

            return View("CreateGame", gameViewModel);
        }

        [HttpPost]
        public ActionResult CreateGame(CreateGameViewModel model)
        {
            var game = Mapper.Map<CreateGameViewModel, Game>(model);

            if (model.SelectedPlatforms.Any())
            {
                game.Platforms = _platformManager.Find(x => model.SelectedPlatforms.Any(f => f == x.Id)).ToList();
            }

            if (model.SelectedGenres.Any())
            {
                game.Genres = _genreManager.Find(x => model.SelectedGenres.Any(f => f == x.Id)).ToList();
            }

            if (model.SelectedPublishers.Any())
            {
                game.Publishers = _publisherManager.Find(x => model.SelectedPublishers.Any(f => f == x.Id)).ToList();
            }

            game.AddingDate = DateTime.UtcNow;
            var request = _gameManager.CreateNewGame(game);

            if (request != HttpStatusCode.Created)
            {
                throw new ValidationException("Invalid form data.");
            }

            return RedirectToAction("GetAllGames");

        }

        [HttpGet]
        public ActionResult EditGame(string gameKey)
        {
            var game = _gameManager.GetGameByKey(gameKey);

            var viewModel = Mapper.Map<Game, CreateGameViewModel>(game);

            var genres = _genreManager.GetAllGenres().OrderBy(a => a.Name).ToList();
            var publishers = _publisherManager.GetAllPublishers().OrderBy(p => p.CompanyName).ToList();
            var platforms = _platformManager.GetAllPlatforms().OrderBy(p => p.Type).ToList();

            viewModel.SelectedPlatforms = game.Platforms?
                .Where(g => platforms.Any(n => n.Id == g.Id))
                .Select(f => f.Id).ToList();

            viewModel.SelectedGenres = game.Genres?
                .Where(g => genres.Any(n => n.Id == g.Id))
                .Select(f => f.Id).ToList();

            viewModel.SelectedPublishers = game.Publishers?
                .Where(g => publishers.Any(n => n.Id == g.Id))
                .Select(f => f.Id).ToList();

            viewModel.AllPublishers = new MultiSelectList(publishers, "Id", "CompanyName", viewModel.SelectedPublishers);
            viewModel.AllPlatforms = new MultiSelectList(platforms, "Id", "Type", viewModel.SelectedPlatforms);
            viewModel.AllGenres = new MultiSelectList(genres, "Id", "Name", viewModel.SelectedGenres);

            ViewBag.GameKey = gameKey;

            return View("EditGame", viewModel);
        }

        [HttpPost]
        public ActionResult EditGame(CreateGameViewModel gameViewModel) // TODO : game editing
        {
            var gameFromDb = _gameManager.GetGameByKey(gameViewModel.Key);

            Mapper.Map(gameViewModel, gameFromDb);

            gameFromDb.Genres.RemoveAll(x => gameViewModel.SelectedGenres.All(f => f != x.Id));
            gameFromDb.Publishers.RemoveAll(x => gameViewModel.SelectedPublishers.All(f => f != x.Id));
            gameFromDb.Platforms.RemoveAll(x => gameViewModel.SelectedPlatforms.All(f => f != x.Id));

            if (gameViewModel.SelectedGenres != null)
            {
                var newGenresIds = gameViewModel.SelectedGenres.Except(gameFromDb.Genres.Select(g => g.Id));
                var newGenres = _genreManager.Find(f => newGenresIds.Any(g => g == f.Id));
                gameFromDb.Genres.AddRange(newGenres);
            }

            if (gameViewModel.SelectedPlatforms != null)
            {
                var newPlatformsIds = gameViewModel.SelectedPlatforms.Except(gameFromDb.Platforms.Select(g => g.Id));
                var newPlatforms = _platformManager.Find(f => newPlatformsIds.Any(g => g == f.Id));
                gameFromDb.Platforms.AddRange(newPlatforms);
            }

            if (gameViewModel.SelectedPublishers != null)
            {
                var newPublishersIds = gameViewModel.SelectedPublishers.Except(gameFromDb.Publishers.Select(g => g.Id));
                var newPublishers = _publisherManager.Find(f => newPublishersIds.Any(g => g == f.Id));
                gameFromDb.Publishers.AddRange(newPublishers);
            }

            _gameManager.EditGame(gameFromDb);

            return RedirectToAction("GetAllGames");
        }

        public ActionResult DeleteGame(int gameId)
        {

            var result = _gameManager.DeleteGameById(gameId);

            if (result != HttpStatusCode.OK)
            {
                throw new ValidationException("Invalid data.");
            }

            return RedirectToAction("GetAllGames");
        }

        public ViewResult GetGameDetails(string key)
        {
            var response = _gameManager.GetGameByKey(key);
            response.CountOfViews++;
            _gameManager.EditGame(response);

            var mapResult = Mapper.Map<Game, GameViewModel>(response);

            return View("GameDetails", mapResult);
        }

        [HttpGet]
        public FileResult DownloadGame(string gameKey)
        {
            string path = Server.MapPath("~/App_Data/KindaGame.txt");

            FileStream fs = new FileStream(path, FileMode.Open);

            string fileType = "application/txt";
            string fileName = "KindaGame.txt";

            return File(fs, fileType, fileName);
        }

        [OutputCache(Duration = 60)]
        public int GetCountOfGames()
        {
            return _gameManager.GetAllGames().Count();
        }

        private FilterViewModel GetFilterModel()
        {
            var filter = (FilterViewModel)Activator.CreateInstance(typeof(FilterViewModel), _genreManager, _platformManager, _publisherManager);

            return filter;
        }
    }
}

GameStore.Web/Controllers/PublisherController.cs
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using GameStore.Domain.Core.DomainModels;
using GameStore.Services.Interfaces;
using GameStore.Web.ViewModels;

namespace GameStore.Web.Controllers
{
    public class PublisherController : Controller
    {
        private readonly IPublisherManager _publisherManager;

        public PublisherController(IPublisherManager publisherManager)
        {
            _publisherManager = publisherManager;
        }
        
        public ActionResult PublisherDetails(string companyName)
        {
            var publisher = _publisherManager.Find(x => x.CompanyName == companyName).SingleOrDefault();

            if (publisher != null)
                return View("PublisherDetails", Mapper.Map<Publisher, PublisherViewModel>(publisher));

            ViewBag.ErrorMessage = $"Publisher \"{companyName}\" was deleted.";

            return View("Error");
        }

        [HttpGet]
        public ActionResult CreatePublisher()
        {
            return View("CreatePublisherForm", new CreatePublisherViewModel());
        }

        [HttpPost]
        public ActionResult CreatePublisher(CreatePublisherViewModel model)
        {
            var newPublisher = Mapper.Map<CreatePublisherViewModel, Publisher>(model);
            var result = _publisherManager.CreateNewPublisher(newPublisher);
            var response = new HttpStatusCodeResult(result);

            return RedirectToAction("GetAllGames", "Game");
        }
        
        public ActionResult DeletePublisher(int publisherId)
        {
            _publisherManager.DeletePublisherById(publisherId);

            return RedirectToAction("GetAllGames","Game");
        }
    }
}

GameStore.Web/Views/Game/AllGames.cshtml
@{
    ViewBag.Title = "AllGames";
}

@using GameStore.Web.Controllers
@using GameStore.Web.ViewModels
@using PagedList.Mvc

@model GamesWithFilterComplexModel

<h2>All Games</h2>

<div hidden class="alert alert-success" id="success-alert" style="position:fixed; right: 8vw; top: 8vh;">
    <strong>Success! </strong>
    Product have added to your cart.
</div>

<div hidden class="alert alert-warning" id="warning-alert" style="position:fixed; right: 8vw; top: 8vh;">
    @*<button type="button" class="close" data-dismiss="alert">x</button>*@
    <strong>Warning! </strong>
    Not enough products in stock.
</div>

@if (Model.FilterOutput == null)
{
    Model.FilterOutput = Session["FilterState"] as FilterOutputModel;
}

<div id="mySidenav" class="sidenav">

    @using (Html.BeginForm("GetAllGames", "Game", FormMethod.Get))
    {
        @Html.AntiForgeryToken()
        @*<a href="javascript:void(0)" class="closebtn" onclick="closeNav()" style="position:fixed">&times;</a>*@
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-horizontal">

            @Html.EditorFor(model => model.FilterOutput.FilterByName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Filter by name..." } })<br />
            @Html.ValidationMessageFor(model => model.Filter.FilterByName, "", new { @class = "text-danger" })<br />
            
            @Html.EditorFor(model => model.FilterOutput.PriceFrom, new { htmlAttributes = new { @class = "form-control", @placeholder = "Price From..." } })<br/>
            @Html.ValidationMessageFor(model => model.Filter.PriceFrom, "", new { @class = "text-danger" })<br />
            
            @Html.EditorFor(model => model.FilterOutput.PriceTo, new { htmlAttributes = new { @class = "form-control", @placeholder = "Price To..." } })<br />
            @Html.ValidationMessageFor(model => model.Filter.PriceTo, "", new { @class = "text-danger" })<br />

            @Html.ListBoxFor(x => x.FilterOutput.SelectedGenres, Model.Filter.AllGenres, new { @class = "chzn-select",  data_placeholder = "Filter by Genres..." })<br />
            @Html.ValidationMessageFor(model => model.Filter.SelectedGenres, "", new { @class = "text-danger" })<br />
            
            @Html.ListBoxFor(x => x.FilterOutput.SelectedPlatforms, Model.Filter.AllPlatforms, new { @class = "chzn-select", data_placeholder = "Filter by Plarforms..." })<br />
            @Html.ValidationMessageFor(model => model.Filter.SelectedPlatforms, "", new { @class = "text-danger" })<br />

            @Html.ListBoxFor(x => x.FilterOutput.SelectedPublishers, Model.Filter.AllPublishers, new { @class = "chzn-select", data_placeholder = "Filter by Publishers..." })<br />
            @Html.ValidationMessageFor(model => model.Filter.SelectedPublishers, "", new { @class = "text-danger" })<br />

            @Html.EnumDropDownListFor(x => x.FilterOutput.OrderByOptions, "Filter by...", new { @class = "form-control" })<br/>
            @Html.EnumDropDownListFor(x => x.FilterOutput.WhenPublished, "When published...", new { @class = "form-control" })<br />
            
            @Html.Label("Items per page")
            @Html.DropDownListFor(x => x.FilterOutput.ItemsPerPage, Model.Filter.ItemsPerPage, new { @class = "form-control" })<br />

        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Confirm filter" class="btn btn-primary" />
            </div>
        </div>
    }
</div>


<!-- Use any element to open the sidenav -->
<button onclick="openNav()" class="btn btn-default" style="float: right">Filter</button>

<div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Key</th>
                <th>Genres</th>
                <th>Platforms</th>
                <th>Publishers</th>
                <th>Comments</th>
                <th>Units in stock</th>
                <th>Price</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.GameList)
            {
                <tr>
                    <td>
                        @item.Name
                    </td>
                    <td>
                        @item.Key
                    </td>
                    <td>
                        @item.Genres
                    </td>
                    <td>
                        @item.Platforms
                    </td>
                    <td>
                        @foreach (var publisher in item.Publishers)
                        {
                            <div>@Html.ActionLink(publisher, "PublisherDetails", "Publisher", new { companyName = publisher }, null)</div>
                        }
                    </td>
                    <td>
                        @item.Comments.Count
                    </td>
                    <td>
                        @item.UnitsInStock
                    </td>
                    <td>
                        $ @item.Price
                    </td>
                    <td>
                        @Html.ActionLink("Details", "GetGameDetails", "Game", new { key = item.Key }, null) |
                        @Html.ActionLink("Edit", "EditGame", "Game", new { gameKey = item.Key }, null) |
                        @Html.ActionLink("Delete", "DeleteGame", "Game", new { gameId = item.Id }, null) |

                        @if (item.UnitsInStock > 0)
                        {
                            <a id="@item.Key" style="cursor: pointer">Buy</a>
                        }
                        else
                        {
                            <a title="Temporarily unavailable" style="pointer-events: none; cursor: default; color: gray">Buy</a>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>


<div class="text-center">
    @Html.PagedListPager(Model.GameList, page => Url.Action("GetAllGames", new { page, filterOutput = Session["FilterState"] }), new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded, DisplayPageCountAndCurrentLocation = true, DisplayItemSliceAndTotal = true })
</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/chosen.jquery.min.js")
    <link href="@Url.Content("~/Content/chosen.min.css")" rel="stylesheet" type="text/css" />
}


<script>

    $(function () {
        $('body').on('click',
            'a:contains("Buy")',
            function (event) {
                $(this)
                $.ajax({
                    url: `/game/${event.currentTarget.id}/buy`,
                    method: 'GET',
                    success: () => {
                        $("#success-alert").show();
                        $("#success-alert").fadeTo(2000, 500).slideUp(500, function () {
                            $("#success-alert").slideUp(500);
                        });

                        if (document.getElementById('cartBadge').innerText) {
                            +document.getElementById('cartBadge').innerText++;
                        } else {
                            document.getElementById('cartBadge').innerText = 1;
                        }
                    },
                    error: () => {
                        $("#warning-alert").show();
                        $("#warning-alert").fadeTo(2000, 500).slideUp(500, function () {
                            $("#warning-alert").slideUp(500);
                        });
                    }
                });
            });
    });

    function openNav() {
        var a = document.getElementById("mySidenav").style.width;
        if (a == "300px") {
            document.getElementById("mySidenav").style.width = "0";
        } else {
            document.getElementById("mySidenav").style.width = "300px";
        }
    }

    /* Set the width of the side navigation to 0 */
    function closeNav() {
        document.getElementById("mySidenav").style.width = "0";
    }

    $(document).ready(function () {
        $('.chzn-select').chosen();
    });

</script>

GameStore.Web/Views/Game/CreateGame.cshtml
@model GameStore.Web.ViewModels.CreateGameViewModel

@{
    ViewBag.Title = "CreateGame";
}
<h2>Create Game</h2>

@Html.EditorForModel()

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/chosen.jquery.min.js")
    <link href="@Url.Content("~/Content/chosen.min.css")" rel="stylesheet" type="text/css" />
}

<script>
    $(document).ready(function () {
        $('.chzn-select').chosen();
    });
</script>

GameStore.Web/Views/Game/EditGame.cshtml
@using System.Web.UI.WebControls
@using GameStore.Web.ViewModels
@model GameStore.Web.ViewModels.CreateGameViewModel

@{
    ViewBag.Title = "EditGame";
}

<h2>EditGame</h2>


@using (Html.BeginForm("EditGame", "Game", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Key, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Key, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Key, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnitsInStock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UnitsInStock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UnitsInStock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Discontinued, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Discontinued, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Discontinued, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SelectedGenres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBox("SelectedGenres", Model.AllGenres, new { @class = "chzn-select col-md-4", data_placeholder = "Genres..." })
                @Html.ValidationMessageFor(model => model.SelectedGenres, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.SelectedPlatforms, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBox("SelectedPlatforms", Model.AllPlatforms, new { @class = "chzn-select col-md-4", data_placeholder = "Platforms..." })
                @Html.ValidationMessageFor(model => model.SelectedPlatforms, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.SelectedPublishers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBox("SelectedPublishers", Model.AllPublishers, new { @class = "chzn-select col-md-4", data_placeholder = "Publishers..." })
                @Html.ValidationMessageFor(model => model.SelectedPublishers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

    <div>
        @Html.ActionLink("Back to List", "GetAllGames", "Game")
    </div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/chosen.jquery.min.js")
    <link href="@Url.Content("~/Content/chosen.min.css")" rel="stylesheet" type="text/css" />
}

<script>
    $(document).ready(function () {
        $('.chzn-select').chosen();
    });
</script>

GameStore.Web/Views/Game/GameDetails.cshtml
@model GameStore.Web.ViewModels.GameViewModel

@{
    ViewBag.Title = "GameDetails";
}

<h2>Game Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Key)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Key)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Genres)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Genres)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Platforms)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Platforms)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AddingDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AddingDate.Date)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CountOfViews)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CountOfViews)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "GetAllGames") |
    @Html.ActionLink("Download", "DownloadGame", new { gameKey = Model.Key }, new { target = "_blanc" }) |
    @Html.ActionLink("Comments", "GetAllCommentsByGameKey", "Comment", new { gameKey = Model.Key }, null)

    @*<button onclick="showOrHideComments">Comments</button>*@
    @*@Ajax.ActionLink("Show Comments", "GetAllCommentsByGameKey", "Comment", new { gameKey = Model.Key }, new AjaxOptions { UpdateTargetId = "incertElement" }) |
        @Html.ActionLink("Buy", "AddToBasket", "Basket", new { gameKey = Model.Key }, null)*@
</p>