GameStore.Web/ViewModels/CommentViewModel.cs
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace GameStore.Web.ViewModels
{
    public class CommentViewModel
    {
        public CommentViewModel()
        {
            RepliesCollection = new List<CommentViewModel>();
        }

        [HiddenInput(DisplayValue = false)]
        public int Id { get; set; }

        [HiddenInput(DisplayValue = false)]
        public int? ParentCommentId { get; set; }

        public List<CommentViewModel> RepliesCollection { get; set; }

        [Required(ErrorMessage = "Required field")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Required field")]
        public string Body { get; set; }

        public string Quote { get; set; }

        public bool IsDeleted { get; set; }

        public bool IsQuote { get; set; }
    }
}

GameStore.Web/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using GameStore.Domain.Core.DomainModels;
using GameStore.Services.Interfaces;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using GameStore.Web.ViewModels;
using WebGrease.Css.Extensions;

namespace GameStore.Web.Controllers
{
    public class CommentController : Controller
    {
        private readonly ICommentManager _commentManager;
        private readonly IGameManager _gameManager;

        private const string duration = "duration";
        private const string messageForDeletedQuote = "Comment was deleted...";

        public CommentController(ICommentManager commentManager, IGameManager gameManager)
        {
            this._commentManager = commentManager;
            _gameManager = gameManager;
        }

        [HttpPost]
        public ActionResult LeaveCommentToGame(Comment comment, string gameKey)
        {
            _commentManager.AddCommentToGame(comment, gameKey);

            return RedirectToAction("GetAllCommentsByGameKey", "Comment", gameKey);
        }

        [HttpPost]
        public ActionResult ReplyToComment(int parentCommentId, Comment newComment, string gameKey, string quote)
        {
            if (quote != null && quote != String.Empty)
            {
                newComment.IsQuote = true;
            }

            _commentManager.AddReplyToComment(newComment, parentCommentId, gameKey);

            return RedirectToAction("GetAllCommentsByGameKey", "Comment", new { gameKey });
        }

        [HttpPost]
        public ActionResult DeleteComment(int commentId, string gameKey)
        {
            var comment = _commentManager.GetById(commentId);
            comment.IsDeleted = true;
            _commentManager.EditComment(comment);

            var childComments = _commentManager.FindByParentId(comment.Id).Where(c => c.IsQuote);
            childComments.ForEach(c => c.Quote = messageForDeletedQuote);
            childComments.ForEach(c=>_commentManager.EditComment(c));

            return RedirectToAction("GetAllCommentsByGameKey", "Comment", new { gameKey });
        }

        [HttpPost]
        public ActionResult Ban(object user, string gameKey, FormCollection form)
        {
            string banDuration = Request.Form[duration].ToString();

            return RedirectToAction("GetAllCommentsByGameKey", "Comment", new { gameKey });
        }

        [HttpGet]
        public ViewResult GetAllCommentsByGameKey(string gameKey)
        {
            ViewBag.GameKey = gameKey;

            var response = this._commentManager.GetAllCommentsByGameKey(gameKey).Where(x => x.CommentId == null);

            var result = Mapper.Map<IEnumerable<Comment>, IEnumerable<CommentViewModel>>(response).ToList();

            return View("CommentsForGame", result);
        }
    }
}

GameStore.Web/Controllers/GameController.cs
using System;
using AutoMapper;
using GameStore.Domain.Core.DomainModels;
using GameStore.Services.Interfaces;
using GameStore.Web.ViewModels;
using PagedList;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Reflection;
using Org.BouncyCastle.Math;

namespace GameStore.Web.Controllers
{
    public class GameController : Controller
    {
        private readonly IGameManager _gameManager;
        private readonly IGenreManager _genreManager;
        private readonly IPlatformManager _platformManager;
        private readonly IPublisherManager _publisherManager;

        public GameController(IGameManager gameManager, IGenreManager genreManager, IPlatformManager platformTypeManager, IPublisherManager publisherManager)
        {
            _gameManager = gameManager;
            _genreManager = genreManager;
            _platformManager = platformTypeManager;
            _publisherManager = publisherManager;
        }

        [HttpGet]
        public ActionResult GetAllGames(FilterOutputModel filterOutput, int? page)
        {
            if (filterOutput == null)
            {
                filterOutput = Session["FilterState"] as FilterOutputModel;
            }

            if (filterOutput.GetType()
                .GetProperties(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static | BindingFlags.Instance)
                .Any(property => property.CanRead && property.GetValue(filterOutput, null) != null))
            {
                var result = _gameManager.GetFilteredResult(Mapper.Map<FilterOutputModel, IFilterModel>(filterOutput));

                int perPage = result.Count();

                if (Int32.TryParse(filterOutput.ItemsPerPage, out int number))
                {
                    if (number != 0) perPage = number;
                }


                var mappingResult = Mapper.Map<IEnumerable<Game>, IEnumerable<GameViewModel>>(result).ToPagedList(page ?? 1, perPage);
                var model = new GamesWithFilterComplexModel() { GameList = mappingResult, Filter = GetFilterModel() };

                Session["FilterState"] = filterOutput;

                return View("AllGames", model);
            }
            else
            {
                Session["FilterState"] = null;

                var gamesFromDb = _gameManager.GetAllGames().ToList();

                var mappingResult = Mapper.Map<IEnumerable<Game>, IEnumerable<GameViewModel>>(gamesFromDb).ToPagedList(page ?? 1, 2);
                var model = new GamesWithFilterComplexModel() { GameList = mappingResult, Filter = GetFilterModel() };

                return View("AllGames", model);
            }
        }

        [HttpGet]
        public ActionResult CreateGame()
        {
            var gameViewModel = new CreateGameViewModel();

            var genresFromDb = _genreManager.GetAllGenres().ToList();
            var platformsFromDb = _platformManager.GetAllPlatforms().ToList();
            var publishersFromDb = _publisherManager.GetAllPublishers().ToList();

            gameViewModel.AllGenres = new MultiSelectList(genresFromDb.OrderBy(i => i.Category), "Id", "Name", "Category");
            gameViewModel.AllPlatforms = new MultiSelectList(platformsFromDb.OrderBy(i => i.Type), "Id", "Type");
            gameViewModel.AllPublishers = new MultiSelectList(publishersFromDb.OrderBy(i => i.CompanyName), "Id", "CompanyName");

            return View("CreateGame", gameViewModel);
        }

        [HttpPost]
        public ActionResult CreateGame(CreateGameViewModel model)
        {
            var game = Mapper.Map<CreateGameViewModel, Game>(model);

            if (model.SelectedPlatforms.Any())
            {
                game.Platforms = _platformManager.Find(x => model.SelectedPlatforms.Any(f => f == x.Id)).ToList();
            }

            if (model.SelectedGenres.Any())
            {
                game.Genres = _genreManager.Find(x => model.SelectedGenres.Any(f => f == x.Id)).ToList();
            }

            if (model.SelectedPublishers.Any())
            {
                game.Publishers = _publisherManager.Find(x => model.SelectedPublishers.Any(f => f == x.Id)).ToList();
            }

            game.AddingDate = DateTime.UtcNow;
            var request = _gameManager.CreateNewGame(game);

            if (request != HttpStatusCode.Created)
            {
                throw new ValidationException("Invalid form data.");
            }

            return RedirectToAction("GetAllGames");

        }

        [HttpGet]
        public ActionResult EditGame(string gameKey)
        {
            var game = _gameManager.GetGameByKey(gameKey);

            var viewModel = Mapper.Map<Game, CreateGameViewModel>(game);

            var genres = _genreManager.GetAllGenres().OrderBy(a => a.Name).ToList();
            var publishers = _publisherManager.GetAllPublishers().OrderBy(p => p.CompanyName).ToList();
            var platforms = _platformManager.GetAllPlatforms().OrderBy(p => p.Type).ToList();

            viewModel.SelectedPlatforms = game.Platforms?
                .Where(g => platforms.Any(n => n.Id == g.Id))
                .Select(f => f.Id).ToList();

            viewModel.SelectedGenres = game.Genres?
                .Where(g => genres.Any(n => n.Id == g.Id))
                .Select(f => f.Id).ToList();

            viewModel.SelectedPublishers = game.Publishers?
                .Where(g => publishers.Any(n => n.Id == g.Id))
                .Select(f => f.Id).ToList();

            viewModel.AllPublishers = new MultiSelectList(publishers, "Id", "CompanyName", viewModel.SelectedPublishers);
            viewModel.AllPlatforms = new MultiSelectList(platforms, "Id", "Type", viewModel.SelectedPlatforms);
            viewModel.AllGenres = new MultiSelectList(genres, "Id", "Name", viewModel.SelectedGenres);

            ViewBag.GameKey = gameKey;

            return View("EditGame", viewModel);
        }

        [HttpPost]
        public ActionResult EditGame(CreateGameViewModel gameViewModel) // TODO : game editing
        {
            var gameFromDb = _gameManager.GetGameByKey(gameViewModel.Key);

            Mapper.Map(gameViewModel, gameFromDb);

            gameFromDb.Genres.RemoveAll(x => gameViewModel.SelectedGenres.All(f => f != x.Id));
            gameFromDb.Publishers.RemoveAll(x => gameViewModel.SelectedPublishers.All(f => f != x.Id));
            gameFromDb.Platforms.RemoveAll(x => gameViewModel.SelectedPlatforms.All(f => f != x.Id));

            if (gameViewModel.SelectedGenres != null)
            {
                var newGenresIds = gameViewModel.SelectedGenres.Except(gameFromDb.Genres.Select(g => g.Id));
                var newGenres = _genreManager.Find(f => newGenresIds.Any(g => g == f.Id));
                gameFromDb.Genres.AddRange(newGenres);
            }

            if (gameViewModel.SelectedPlatforms != null)
            {
                var newPlatformsIds = gameViewModel.SelectedPlatforms.Except(gameFromDb.Platforms.Select(g => g.Id));
                var newPlatforms = _platformManager.Find(f => newPlatformsIds.Any(g => g == f.Id));
                gameFromDb.Platforms.AddRange(newPlatforms);
            }

            if (gameViewModel.SelectedPublishers != null)
            {
                var newPublishersIds = gameViewModel.SelectedPublishers.Except(gameFromDb.Publishers.Select(g => g.Id));
                var newPublishers = _publisherManager.Find(f => newPublishersIds.Any(g => g == f.Id));
                gameFromDb.Publishers.AddRange(newPublishers);
            }

            _gameManager.EditGame(gameFromDb);

            return RedirectToAction("GetAllGames");
        }

        public ActionResult DeleteGame(int gameId)
        {

            var result = _gameManager.DeleteGameById(gameId);

            if (result != HttpStatusCode.OK)
            {
                throw new ValidationException("Invalid data.");
            }

            return RedirectToAction("GetAllGames");
        }

        public ViewResult GetGameDetails(string key)
        {
            var response = _gameManager.GetGameByKey(key);
            response.CountOfViews++;
            _gameManager.EditGame(response);

            var mapResult = Mapper.Map<Game, GameViewModel>(response);

            return View("GameDetails", mapResult);
        }

        [HttpGet]
        public FileResult DownloadGame(string gameKey)
        {
            string path = Server.MapPath("~/App_Data/KindaGame.txt");

            FileStream fs = new FileStream(path, FileMode.Open);

            string fileType = "application/txt";
            string fileName = "KindaGame.txt";

            return File(fs, fileType, fileName);
        }

        [OutputCache(Duration = 60)]
        public int GetCountOfGames()
        {
            return _gameManager.GetAllGames().Count();
        }

        private FilterViewModel GetFilterModel()
        {
            var filter = (FilterViewModel)Activator.CreateInstance(typeof(FilterViewModel), _genreManager, _platformManager, _publisherManager);

            return filter;
        }
    }
}

GameStore.Web/Views/Comment/CommentBlockPartial.cshtml
@model GameStore.Web.ViewModels.CommentViewModel


<dl id="comment" class="dl-horizontal">
    @if (Model.Quote != String.Empty && Model.Quote != null)
    {
        if (Model.IsQuote)
        {
            <blockquote>
                <q>@Model.Quote</q>
            </blockquote>
        }
    }
    <dt>
        @Html.DisplayName("Name")
    </dt>
    <dd>
        @Html.DisplayFor(c => Model.Name)
    </dd>
    <dt>
        @Html.DisplayName("Text")
    </dt>
    <dd id="body_@Model.Id">
        @if (!Model.IsDeleted)
        {
            @Html.DisplayFor(c => Model.Body)
        }
        else
        {
            <span style="color: red">Comment was deleted..</span>
        }
    </dd>
</dl>

    @if (!Model.IsDeleted)
    {
<div>
    <button class="replyBtn" id="@Model.Id" @*onclick="newReply(this.id)"*@>Reply</button> |
    <button class="quoteBtn" id="@Model.Id" @*onclick="quote(this.id)"*@>Quote</button> |
    <button class="deleteBtn" id="@Model.Id" @*onclick="deleteComment(this.id)"*@>Delete</button> |
    <button class="banBtn" id="@Model.Id" @*onclick="banComment(this.id)"*@>Ban</button>
    <hr />
</div>
    }

@if (Model.RepliesCollection.Count > 0)
{
    foreach (var comment in Model.RepliesCollection)
    {
        <ul style="margin-left: 30px;">
            @Html.Partial("CommentBlockPartial", comment)
        </ul>
    }

}

@using (Html.BeginForm("Ban", "Comment", new { commentId = Model.Id, gameKey = ViewBag.GameKey }, FormMethod.Post))
{
    <div class="modal fade" id="ban_@Model.Id" role="dialog">
        <div class="modal-dialog modal-sm vertical-align-center">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Confirm delete</h4>
                </div>
                <div class="modal-body">
                    Are you sure you want to <b>ban</b> this user?
                </div>
                <div class="form-horizontal">
                    <div class="form-group">
                        <select class="center-block" name="duration">
                            <option value="hour">1 hour</option>
                            <option value="day">1 day</option>
                            <option value="week">1 week</option>
                            <option value="month">1 month</option>
                            <option value="permanent">Permanent</option>
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-default">Ban</button>
                    <button type="button" data-dismiss="modal" class="btn btn-default">Back</button>
                </div>
            </div>
        </div>
    </div>
}

@using (Html.BeginForm("DeleteComment", "Comment", new { commentId = Model.Id, gameKey = ViewBag.GameKey }, FormMethod.Post))
{
    <div class="modal fade" id="delete_@Model.Id" role="dialog">
        <div class="modal-dialog modal-sm vertical-align-center">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Confirm delete</h4>
                </div>
                <div class="modal-body">
                    Are you sure you want to delete the comment?
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-default">Yes</button>
                    <button type="button" data-dismiss="modal" class="btn btn-default">No</button>
                </div>
            </div>
        </div>
    </div>
}

@using (Html.BeginForm("ReplyToComment", "Comment", new { parentCommentId = Model.Id, gameKey = ViewBag.GameKey }, FormMethod.Post))
{
    <div class="modal fade" id="reply_@Model.Id" role="dialog">
        <div class="modal-dialog modal-lg center-block">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">New comment</h4>
                </div>
                <div class="modal-body">
                    <div class="form-horizontal">
                        <div class="form-group">
                            @Html.Label("Name", new { @class = "control-label col-md-1" })
                            <input name="Name" placeholder="Name..." />
                        </div>
                        <div class="form-group">
                            @Html.Label("Text", new { @class = "control-label col-md-1" })
                            <textarea name="Body" placeholder="Commentary..."></textarea>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-default">Add</button>
                    <button type="button" data-dismiss="modal" class="btn btn-default">Cancel</button>
                </div>
            </div>
        </div>
    </div>
}

@using (Html.BeginForm("ReplyToComment", "Comment", new { parentCommentId = Model.Id, gameKey = ViewBag.GameKey }, FormMethod.Post))
{
    <div class="modal fade" id="quote_@Model.Id" role="dialog">
        <div class="modal-dialog modal-lg center-block">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">New comment</h4>
                </div>
                <div class="modal-body">
                    <blockquote>
                        <input name="Quote" id="modalBody_@Model.Id" readonly="" />
                    </blockquote>
                    <div class="form-horizontal">
                        <div class="form-group">
                            @Html.Label("Name", new { @class = "control-label col-md-1" })
                            <input name="Name" placeholder="Name..." />
                        </div>
                        <div class="form-group">
                            @Html.Label("Text", new { @class = "control-label col-md-1" })
                            <textarea name="Body" placeholder="Commentary..."></textarea>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-default">Add</button>
                    <button type="button" data-dismiss="modal" class="btn btn-default">Cancel</button>
                </div>
            </div>
        </div>
    </div>
}

GameStore.Web/Views/Comment/CommentsForGame.cshtml
@using System.Drawing
@using GameStore.Web.ViewModels
@using Microsoft.Ajax.Utilities
@model IEnumerable<GameStore.Web.ViewModels.CommentViewModel>

@{
    ViewBag.Title = "CommentsForGame";
}

<h2>@ViewBag.GameKey Comments</h2>
<hr />

<div>
    @foreach (var comment in Model)
    {
        @Html.Partial("CommentBlockPartial", comment)
    }

</div>


@Scripts.Render("~/bundles/jqueryval")

@Html.Partial("NewCommentForm", new CommentViewModel())

<p>
    @Html.ActionLink("Back", "GetGameDetails", "Game", new { key = ViewBag.GameKey }, null)
</p>

<script type="text/javascript">

    // jQuery instead native js

    $('.replyBtn').on("click",
        function() {
            $(`#reply_${this.id}`).modal('show');
        });

    $('.quoteBtn').on("click",
        function() {
            var commentText = $(`#body_${this.id}`).text();
            var qoute = $(`#modalBody_${this.id}`);
            qoute.val(commentText);

            $(`#quote_${this.id}`).modal('show');
        });

    $('.deleteBtn').on("click",
        function() {
            const idStr = `delete_${this.id}`;

            $(`#${idStr}`).modal('show');
        });

    $('.banBtn').on("click",
        function () {
            const idStr = `ban_${this.id}`;

            $(`#${idStr}`).modal('show');
        });

</script>

GameStore.Web/Views/Comment/NewCommentForm.cshtml
@using GameStore.Web.ViewModels
@using Microsoft.Ajax.Utilities

@model CommentViewModel


<h4>New Comment</h4>


@using (Html.BeginForm("LeaveCommentToGame", "Comment", FormMethod.Post))
{
    <div class="table-bordered">
        <div class="form-group">
            @Html.LabelFor(m => m.Name, new { @class = "control-label col-md-2" })
            @Html.EditorFor(m => m.Name, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
            @*@Html.Label("Name", new {@class = "control-label col-md-2"})
        @Html.Editor("Name", new {@class = "form-control"})*@
        </div>
        <div class="form-group">
            @Html.Label("Text", new { @class = "control-label col-md-2" })
            @Html.TextAreaFor(m => m.Body, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            @*@Html.Label("Text", new { @class = "control-label col-md-2" })
        @Html.TextArea("Body", new { @class = "form-control" })*@
        </div>
        <div class="form-group">
            <div class="col-md-offset-1 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}







@*@foreach (var comment in Model)
{
    <dl>
        <dt>
            @Html.DisplayName("Name")
        </dt>
        <dd>
            @Html.DisplayFor(c => comment.Name)
        </dd>
        <dt>
            @Html.DisplayName("Text")
        </dt>
        <dd>
            @Html.DisplayFor(c => comment.Body)
        </dd>
    </dl>
    <div>
        <button id="newReplyBtn" class="btn btn-default" onclick="newReplyForm">Reply</button> |
        <button id="newReplyBtn" class="btn btn-default" onclick="newReplyForm">Quote</button> <!--TODO : quote-->
    </div>
    <hr />
}*@



@*<div id="comment">
    <button id="newCommentBtn" class="btn btn-default" onclick="newCommentForm">Leave comment to game</button>
</div>

@using (Html.BeginForm("LeaveCommentToGame", "Comment", FormMethod.Post, new { id = "newCommentForm", style = "display:none" }))
{
    <div class="form-horizontal">
        <div class="form-group">
            @Html.Label("Name", new { @class = "control-label col-md-2" })
            @Html.Editor("Name", new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.Label("Text", new { @class = "control-label col-md-2" })
            @Html.TextArea("Body", new { @class = "form-control" })
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.ActionLink("Leave Comment", "LeaveCommentToGame", "Comment", new { }, new { @class = "btn btn-default" })
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}


<script>

    var isFormOpen = true;

    $(document).ready(function () {

        $("#newCommentBtn").click(function () {

            if (isFormOpen) {

                document.getElementById("newCommentBtn").innerText = "Close form";

                $("#newCommentForm").show();
                isFormOpen = false;

            } else {

                document.getElementById("newCommentBtn").innerText = "Leave comment to game";
                $("#newCommentForm").hide();
                isFormOpen = true;
            }
        });
    });


</script>*@